#!/usr/bin/env sh
# Generates scripts/config.js (git-ignored) from .env so the extension knows
# where the Ollama server is. Re-run it whenever you change .env, then reload
# the extension in chrome://extensions.
set -eu
cd "$(dirname "$0")/.."

if [ ! -f .env ]; then
  echo "No .env found. Create one first:  cp .env.example .env" >&2
  exit 1
fi

set -a
. ./.env
set +a

: "${OLLAMA_URL:?OLLAMA_URL is not set in .env}"
: "${OLLAMA_MODEL:=xplain-hate}"
OLLAMA_URL="${OLLAMA_URL%/}"

cat > scripts/config.js <<JS
// AUTO-GENERATED by scripts/generate-config.sh from .env. Do not edit or commit.
const XPLAIN_CONFIG = {
  OLLAMA_URL: "${OLLAMA_URL}",
  OLLAMA_MODEL: "${OLLAMA_MODEL}"
};
JS

echo "Wrote scripts/config.js (OLLAMA_URL=${OLLAMA_URL}, OLLAMA_MODEL=${OLLAMA_MODEL})"
